# Site Info
title: "The Plain"
description: "A minimalist Jekyll theme"
author_name: "Kyongshik Lee"
logo_url: https://api.github.com/uses/kyongs # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url: https://kyongs.github.io
baseurl: /the-plain
permalink: /:title # Post permalink
timezone: Asia/Seoul
mathjax: false # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Site Build
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed

# Other Params
include: ["robots.txt"]
exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: "null"
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "posts"
    values:
      layout: "post"
